name: Java CI / CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 1.8, 1.14 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Execute permission
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: chmod +x gradlew
      - name: Build with Gradle (*nix)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: ./gradlew build
      - name: Build with Gradle (Windows)
        if: matrix.os == 'windows-latest'
        run: .\gradlew.bat build
